name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install sdl2

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_HEADLESS_TESTS=ON

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Run SDL tests in CI mode
        run: |
          cd build/bin
          # macOS needs special handling for mouse automation in headless mode
          # We'll use the CI mode flag we're adding to the test application
          ./RobotCPPSDLTest --ci-mode --run-tests

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Use the official vcpkg cache action
      - name: Setup vcpkg
        uses: friendlyanon/setup-vcpkg@v1

      - name: Install SDL2
        run: |
          vcpkg install sdl2:x64-windows
        shell: bash

      - name: Configure
        shell: powershell
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -DBUILD_HEADLESS_TESTS=ON

      - name: Build
        shell: powershell
        run: |
          cd build
          cmake --build . --config Release

      - name: Run SDL tests in CI mode
        shell: powershell
        run: |
          cd build\bin\Release
          .\RobotCPPSDLTest.exe --ci-mode --run-tests
